export const START_LISTERNING_TO_FLAT= 'START_LISTERNING_TO_FLAT';
export const START_LISTERNING_TO_FILE= 'START_LISTERNING_TO_FILE';
export const LISTERNING_TO_FILE_RECEIVE_CONTENT= 'LISTERNING_TO_FILE_RECEIVE_CONTENT';
export const DISABLE_DRAGABLE_FLAT= 'DISABLE_DRAGABLE_FLAT';
export const ENABLE_DRAGABLE_FLAT= 'ENABLE_DRAGABLE_FLAT';
export const NODE_CUT= 'NODE_CUT';
