//init control
export const RECEIVE_NODES_INIT = 'RECEIVE_NODES_INIT';
export const RECEIVE_NODES_CONTENT = 'RECEIVE_NODES_CONTENT';
export const RECEIVE_NODES_FINISHED = 'RECEIVE_NODES_FINISHED';
export const RECEIVE_NODES_FAILED = 'RECEIVE_NODES_FAILED';
export const UPDATE_REF = 'UPDATE_REF';


//single node actions
export const CREATE_NODE = 'CREATE_NODE';
export const UPDATE_NODE = 'UPDATE_NODE';
export const DELETE_NODE = 'DELETE_NODE';


export const START_LISTERNING_TO_FLAT= 'START_LISTERNING_TO_FLAT';
export const DISABLE_DRAGABLE_FLAT= 'DISABLE_DRAGABLE_FLAT';
export const ENABLE_DRAGABLE_FLAT= 'ENABLE_DRAGABLE_FLAT';
export const NODE_CUT= 'NODE_CUT';
