export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';

export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';

export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';

export const CHANGE_CURRENT_FOCUS = 'CHANGE_CURRENT_FOCUS';

export const CUT_NODE = 'CUT_NODE';
export const START_LISTENING = 'START_LISTENING';

