export const CLOSE_LOGIN_MODAL= 'CLOSE_LOGIN_MODAL';
export const OPEN_LOGIN_MODAL= 'OPEN_LOGIN_MODAL';
export const OPEN_MODIFY_FILE_MODAL= 'OPEN_MODIFY_FILE_MODAL';
export const CLOSE_MODIFY_FILE_MODAL= 'CLOSE_MODIFY_FILE_MODAL';
export const TOGGLE_POMODARIO= 'TOGGLE_POMODARIO';
export const TOGGLE_TIMELINE= 'TOGGLE_TIMELINE';
