export default {
	// MISC
	FIREBASE: 'https://thisisatestapp.firebaseio.com/items/test4/',
    //'https://burning-torch-9051.firebaseio.com/notes/users/simplelogin:f03ad24b-e53c-4a0b-aceb-ee09655742c8/files/BN-1457183926722-SLM8n/nodes/'
    //this.ref = new Firebase('https://burning-torch-9051.firebaseio.com/notes/users/simplelogin:f03ad24b-e53c-4a0b-aceb-ee09655742c8/files/BN-1457183852775-qAKrG/nodes/')

	// UI FEEDBACK ACTIONS
	DISPLAY_ERROR: 'DISPLAY_ERROR',
	DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
	DISMISS_FEEDBACK: 'DISMISS_FEEDBACK',

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: 'ATTEMPTING_LOGIN',
	LOGIN_USER: 'LOGIN_USER',
	LOGOUT: 'LOGOUT',

	// AUTH STATES
	LOGGED_IN: 'LOGGED_IN',
	ANONYMOUS: 'ANONYMOUS',
	AWAITING_AUTH_RESPONSE: 'AWAITING_AUTH_RESPONSE',

	// ARTICLE ACTIONS
	RECEIVE_ARTICLES_DATA: 'RECEIVE_ARTICLES_DATA',
	AWAIT_NEW_ARTICLE_RESPONSE: 'AWAIT_NEW_ARTICLE_RESPONSE',
	RECEIVE_NEW_ARTICLE_RESPONSE: 'RECEIVE_NEW_ARTICLE_RESPONSE',
	START_ARTICLE_EDIT: 'START_ARTICLE_EDIT',
	FINISH_ARTICLE_EDIT: 'FINISH_ARTICLE_EDIT',
	SUBMIT_ARTICLE_EDIT: 'SUBMIT_ARTICLE_EDIT',

	// ARTICLE STATES
	EDITING_ARTICLE: 'EDITING_ARTICLE',
	SUBMITTING_ARTICLE: 'SUBMITTING_ARTICLE',
  CHANGE_VISIBILITY_FILTER: 'CHANGE_VISIBILITY_FILTER',

  //POMODARIO
  CHANGE_STATE_POMODARIO: "CHANGE_STATE_POMODARIO",
  SHOW_POMODARIO: "SHOW_POMODARIO",
  HIDE_POMODARIO: "HIDE_POMODARIO",
  TOGLE_POMODARIO: "TOGLE_POMODARIO",
  ESTIMATE_POMODARIO_PLUS: "ESTIMATE_POMODARIO_PLUS",
  ESTIMATE_POMODARIO_MINUS: "ESTIMATE_POMODARIO_MINUS",
  ACTUAL_POMODARIO_PLUS: "ACTUAL_POMODARIO_PLUS",
  ACTUAL_POMODARIO_MINUS: "ACTUAL_POMODARIO_MINUS",
  CHANGE_REF_KEY: "CHANGE_REF_KEY",
};
