export const GET_FILE_LIST= 'GET_FILE_LIST';
export const FILE_CREATED= 'FILE_CREATED';
export const FILE_DELETED= 'FILE_DELETED';

export const UPDATE_MD_CONTENT= 'UPDATE_MD_CONTENT';
export const START_MD_UPDATE_CONTENT= 'START_MD_UPDATE_CONTENT';
export const FINISH_MD_UPDATE_CONTENT= 'FINISH_MD_UPDATE_CONTENT';

export const EDITOR_CHANGE_HEADER= 'EDITOR_CHANGE_HEADER';
export const EDITOR_CHANGE_CONTENT= 'EDITOR_CHANGE_CONTENT';
export const EDITOR_CHANGE_RENDER= 'EDITOR_CHANGE_RENDER';
export const EDITOR_COMPLETE= 'EDITOR_COMPLETE';

export const TOGGLE_EDIT= 'TOGGLE_EDIT';
  
