export const POMODARIO_START = "POMODARIO_START"
export const POMODARIO_DONE = "POMODARIO_DONE"
export const POMODARIO_ABORT = "POMODARIO_ABORT"
export const POMODARIO_SET_VALUE = "POMODARIO_SET_VALUE"
