export const SIGN_IN_SUCCESS= 'SIGN_IN_SUCCESS';
export const SIGN_IN_ONGOING= 'SIGN_IN_ONGOING';
export const SIGN_IN_FAILED= 'SIGN_IN_FAILED';
export const SIGN_OUT_SUCCESS= 'SIGN_OUT_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_INIT = 'CREATE_USER_INIT';
export const CREATE_USER_ONGOING = 'CREATE_USER_ONGOING';


export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';


