export const SIGN_IN_SUCCESS= 'SIGN_IN_SUCCESS';
export const SIGN_OUT_SUCCESS= 'SIGN_OUT_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';


