export const GET_FILES_SUCCESS= 'GET_FILES_SUCCESS';
export const GET_FILES_CONTENT_SUCCESS= 'GET_FILES_CONTENT_SUCCESS';
export const PUSH_TO_TAB= 'PUSH_TO_TAB';
export const POP_TO_TAB= 'POP_TO_TAB';
export const GET_FILE_META_SUCCESS= 'GET_FILE_META_SUCCESS';

export const START_EDIT_FILE_NAME= 'START_EDIT_FILE_NAME';
export const FINISH_EDIT_FILE_NAME= 'FINISH_EDIT_FILE_NAME';

export const ENABLE_EDIT_LAYOUT = "ENABLE_EDIT_LAYOUT"
export const DISABLE_EDIT_LAYOUT = "DISABLE_EDIT_LAYOUT"
